### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by haccy** [ytdl-patched/ytdl-patched#14]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

TypeError occured when downloading a video.

yt-dlp version 2021.12.27 --> **OK**
ytdl-patched version 2022.01.06.1641468523 --> **OK**
ytdl-patched version 2022.01.08.1641643854 --> **NG**

### Verbose log

```shell
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] ytdl-patched version 2022.01.08.1641643854  (exe_red)
[debug]      from commit 9a8a7773f
[debug]      based on 3cf5429a2
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.7.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg n4.4.1-12-gb4da29fee1-20211231 (setts), ffprobe n4.4.1-12-gb4da29fee1-20211231, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[TVer] Downloading JSON metadata
[TVer] [debug] Fetching webpage from https://tver.jp/api/access_token.php
[debug] [TVer] Extracting URL: https://tver.jp/corner/f0094803
[TVer] f0094803: Downloading JSON metadata
[TVer] [debug] Fetching webpage from https://api.tver.jp/v4/corner/f0094803?token=t1.1673184327.eyJhcGlrZXkiOiJlMjRmYWEyMS0zMTNjLTRjNjItYjlkMi0wNzJmMjI3ZWVkZGQiLCJ1c2VyIjoiZWEyOWI0ZmQtZDc1Ny00MGUzLWYyOTMtOTU5M2Y0MjEwMWU4In0.66231969.6c6a11b534078de746c6298ca4d4b62c
[debug] [brightcove:new] Extracting URL: http://players.brightcove.net/6191645753001/default_default/index.html?videoId=ref:4o54810002_20220108#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22JP%22%5D%7D
[debug] Using fake IP 133.127.143.250 (JP) as X-Forwarded-For
[debug] Loading brightcove.6191645753001_default from cache
[brightcove:new] ref:4o54810002_20220108: Downloading JSON metadata
[brightcove:new] [debug] Fetching webpage from https://edge.api.brightcove.com/playback/v1/accounts/6191645753001/videos/ref:4o54810002_20220108
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1421, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1501, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
  File "yt_dlp\extractor\brightcove.py", line 688, in _real_extract
  File "yt_dlp\extractor\brightcove.py", line 485, in _parse_brightcove_metadata
  File "yt_dlp\extractor\common.py", line 2180, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\adobepass.py", line 1360, in _download_webpage_handle
TypeError: 'NoneType' object is not iterable

[debug] Cleaning up 3 streams
```

**Comment by Lesmiscore** [comment]
Fixed. Update to new version coming in 20 minutes. Thanks
