### ISSUE TITLE
ffmpeg command error

### ISSUE THREAD

**Issue by afterdelight** [ytdl-patched/ytdl-patched#20]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm on windows platform and I installed ytdl-patched through 'pip install https://github.com/ytdl-patched/ytdl-patched/archive/refs/heads/ytdlp.zip'

When using command: --ffmpeg-location "D:\Program Files\ffmpeg\bin\ffmpeg.exe"
I got this error:

----------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------

And when removing the command, it works. 
Pls help.

### Verbose log

```shell
Traceback (most recent call last):
  File "c:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python39\Scripts\youtube-dl.exe\__main__.py", line 7, in <module>
  File "c:\python\python39\lib\site-packages\yt_dlp\__init__.py", line 891, in main
    _real_main(argv)
  File "c:\python\python39\lib\site-packages\yt_dlp\__init__.py", line 852, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "c:\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 740, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **compat_kwargs(pp_def)),
  File "c:\python\python39\lib\site-packages\yt_dlp\postprocessor\embedthumbnail.py", line 43, in __init__
    FFmpegPostProcessor.__init__(self, downloader)
  File "c:\python\python39\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 81, in __init__
    self._determine_executables()
  File "c:\python\python39\lib\site-packages\yt_dlp\postprocessor\ffmpeg.py", line 184, in _determine_executables
    if self._versions[p]:
KeyError: 'ffmpeg'
```

**Comment by Lesmiscore** [comment]
The template asks you to paste full log like this:

```
$ ytdl -v
[debug] Command-line config: ['-v']
[debug] User config "/home/lesmi/.config/ytdl-patched/config": ['--cookies=$HOME/ck.txt', '--escape-long-names', '--extractor-args', 'youtube:preferred_langs=ja', '--remux', 'f4v>mkv', '--ffmpeg-loc', '/mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffmpeg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] ytdl-patched version 2022.03.29.1648514349  (homebrew)
[debug]      from commit 7cdb66d5f
[debug]      based on 8a7f68d0b
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.12 (CPython 64bit) - Linux-5.13.0-35-generic-x86_64-with-glibc2.31
[debug] Checking exe version: /mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffmpeg -bsfs
[debug] Checking exe version: /mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffprobe -bsfs
[debug] exe versions: ffmpeg n4.4.1-3-ge16ff82624-20211127 (setts), ffprobe n4.4.1-3-ge16ff82624-20211127, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/youtube-dl", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.3.29.1648514349', 'console_scripts', 'youtube-dl')())
  File "/home/linuxbrew/.linuxbrew/Cellar/ytdl-patched/1648514349/libexec/lib/python3.9/site-packages/yt_dlp/__init__.py", line 891, in main
    _real_main(argv)
  File "/home/linuxbrew/.linuxbrew/Cellar/ytdl-patched/1648514349/libexec/lib/python3.9/site-packages/yt_dlp/__init__.py", line 852, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/home/linuxbrew/.linuxbrew/Cellar/ytdl-patched/1648514349/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 740, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **compat_kwargs(pp_def)),
  File "/home/linuxbrew/.linuxbrew/Cellar/ytdl-patched/1648514349/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 604, in __init__
    super(FFmpegVideoConvertorPP, self).__init__(downloader)
  File "/home/linuxbrew/.linuxbrew/Cellar/ytdl-patched/1648514349/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 81, in __init__
    self._determine_executables()
  File "/home/linuxbrew/.linuxbrew/Cellar/ytdl-patched/1648514349/libexec/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 184, in _determine_executables
    if self._versions[p]:
KeyError: 'ffmpeg'
```

Anyway I can take a look into it

**Comment by Lesmiscore** [comment]
```
$ ./yt-dlp.sh -v --ffmpeg-loc /mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffmpeg
[debug] Command-line config: ['-v', '--ffmpeg-loc', '/mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffmpeg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 8a7f68d0b
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-35-generic-x86_64-with-glibc2.29
[debug] Checking exe version: /mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffmpeg -bsfs
[debug] Checking exe version: /mnt/extra-storage/ffmpeg/ffmpeg-n4.4.1-3-ge16ff82624-linux64-gpl-4.4/bin/ffprobe -bsfs
[debug] exe versions: ffmpeg n4.4.1-3-ge16ff82624-20211127 (setts), ffprobe n4.4.1-3-ge16ff82624-20211127, rtmpdump 2.4
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Traceback (most recent call last):
  File "/home/lesmi/yt-dlp/yt_dlp/__main__.py", line 19, in <module>
    yt_dlp.main()
  File "/home/lesmi/yt-dlp/yt_dlp/__init__.py", line 869, in main
    _real_main(argv)
  File "/home/lesmi/yt-dlp/yt_dlp/__init__.py", line 830, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/home/lesmi/yt-dlp/yt_dlp/YoutubeDL.py", line 687, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **compat_kwargs(pp_def)),
  File "/home/lesmi/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 1123, in __init__
    super().__init__(downloader)
  File "/home/lesmi/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 69, in __init__
    self._determine_executables()
  File "/home/lesmi/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 162, in _determine_executables
    if self._versions[p]:
KeyError: 'ffmpeg'
```
This is absolutely a bug from yt-dlp master, say 8a7f68d0b12d0f4910a15b59a3ec090bbf83b6f2

**Comment by afterdelight** [comment]
ty man it works now
