### ISSUE TITLE
--parse-metadata error: 'MetadataParserPP' has no attribute 'BACKLOG_UNSET'

### ISSUE THREAD

**Issue by afterdelight** [ytdl-patched/ytdl-patched#28]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

got ERROR: type object 'MetadataParserPP' has no attribute 'BACKLOG_UNSET'
when using --parse-metadata

### Verbose log

```shell
F:\downloader\iwara.tv\dl>//ytdl-patched https://www.iwara.tv/videos/axgjgi1pkupwgz4k?playlist=107712 -f best
The filename, directory name, or volume label syntax is incorrect.

F:\downloader\iwara.tv\dl>ytdl-patched -a 000MMD_links.txt --conf config_iwara --parse-metadata "%(uploader)s:%(extractor)s" -v
[debug] Command-line config: ['-a', '000MMD_links.txt', '--conf', 'config_iwara', '--parse-metadata', '%(uploader)s:%(extractor)s', '-v']
[debug] | Config "config_iwara": ['--continue', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--embed-thumbnail', '--abort-on-unavailable-fragment', '-o', '%(uploader)s\\%(title)s [%(id)s].%(ext)s', '--download-archive', 'downloaded.txt', '-f', 'Source/540p/360p', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin', '--no-lock']
[debug] User config "C:\Users\X\AppData\Roaming\yt-dlp\config": ['--continue', '--format-sort', 'vbr,abr', '--http-chunk-size', '1M', '--buffer-size', '16K', '--sub-lang', 'english', '--embed-metadata', '--abort-on-unavailable-fragment', '-o', '%(title)s [%(id)s].%(ext)s', '--ffmpeg-location', 'D:\\Program Files\\ffmpeg\\bin', '--no-lock']
[debug] Batch file urls: ['https://ecchi.iwara.tv/videos/03yedh9lbizq1kq8?language=en', 'https://ecchi.iwara.tv/videos/18kqetlxjt3w8wd3?language=en', 'https://ecchi.iwara.tv/videos/25xbni92aixod0wo?language=en', 'https://ecchi.iwara.tv/videos/4jqbmudrwcwmoqwl?language=en', 'https://ecchi.iwara.tv/videos/6a8als43auo2aezk?language=en', 'https://ecchi.iwara.tv/videos/6zq9zc43auol8kbv?language=en', 'https://ecchi.iwara.tv/videos/7v5rxslm6hgrq3ao?language=en', 'https://ecchi.iwara.tv/videos/88jg3t32ytlbzyvk?language=en', 'https://ecchi.iwara.tv/videos/9zopqhkyxhzv2omq?language=en', 'https://ecchi.iwara.tv/videos/aljzzhvylt72jrgy?language=en', 'https://ecchi.iwara.tv/videos/bnawwf4byu38xepq?language=en', 'https://ecchi.iwara.tv/videos/bzq64f4byu3gvbkq?language=en', 'https://ecchi.iwara.tv/videos/deq7wfo2btkdlo2b?language=en', 'https://ecchi.iwara.tv/videos/dmvr7io2btklywam?language=en', 'https://ecchi.iwara.tv/videos/ekvzasjv9umm2gkk?language=en', 'https://ecchi.iwara.tv/videos/gklk6soqzt7zw2pa?language=en', 'https://ecchi.iwara.tv/videos/gl7gdfxovhovz05p?language=en', 'https://ecchi.iwara.tv/videos/gmjyjuoqzt7a9zkk?language=en', 'https://ecchi.iwara.tv/videos/j006wtz5ytej9jjn?language=en', 'https://ecchi.iwara.tv/videos/j090xiz5ytejvmq1?language=en', 'https://ecchi.iwara.tv/videos/kapz8ukgvhqwqme0?language=en', 'https://ecchi.iwara.tv/videos/kxymrhkgvhq5ol2a?language=en', 'https://ecchi.iwara.tv/videos/l0jb6ckwlh8oamp1?language=en', 'https://ecchi.iwara.tv/videos/ldyazhl85hwr3pvr?language=en', 'https://ecchi.iwara.tv/videos/lwnzwhkwlh8grypd?language=en', 'https://ecchi.iwara.tv/videos/lyo9rukwlh8kwkgb?language=en', 'https://ecchi.iwara.tv/videos/make3crjmu8y4klg?language=en', 'https://ecchi.iwara.tv/videos/mjr0xc3bntozmmgb?language=en', 'https://ecchi.iwara.tv/videos/nmpaatgyjtpbzkml?language=en', 'https://ecchi.iwara.tv/videos/ovalos6z0c18aqjy?language=en', 'https://ecchi.iwara.tv/videos/pxaxbsd6vcok2emp?language=en', 'https://ecchi.iwara.tv/videos/q8qy1sy2xtlpjvzd?language=en', 'https://ecchi.iwara.tv/videos/qm7jqhy2xtlvmodo?language=en', 'https://ecchi.iwara.tv/videos/qykebcgzasrlyewa?language=en', 'https://ecchi.iwara.tv/videos/vo529hrdgue9oeaq?language=en', 'https://ecchi.iwara.tv/videos/voyk4srdgue9k0r6?language=en', 'https://ecchi.iwara.tv/videos/wklyehgnlsymomol?language=en', 'https://ecchi.iwara.tv/videos/wpgbkh1xquqm0wjp?language=en', 'https://ecchi.iwara.tv/videos/wzj0kignlsyla75x?language=en', 'https://ecchi.iwara.tv/videos/xk2qjiyd5uwr1n6b?language=en', 'https://ecchi.iwara.tv/videos/2w9y0h92aiqajv7n?language=en', 'https://ecchi.iwara.tv/videos/45bz4hdrwcyjxgaz?language=en', 'https://ecchi.iwara.tv/videos/5vob5sboghwx7j4m?language=en', 'https://ecchi.iwara.tv/videos/6r7g5i43auonmo3q?language=en', 'https://ecchi.iwara.tv/videos/7oywzslm6hmmjo48?language=en', 'https://ecchi.iwara.tv/videos/ak2bouvylt7k4edb?language=en', 'https://ecchi.iwara.tv/videos/bkmjgh4byu34qrra?language=en', 'https://ecchi.iwara.tv/videos/g8pqwhxovhowvxbg?language=en', 'https://ecchi.iwara.tv/videos/gpaqpfoqzt7z4be8?language=en', 'https://ecchi.iwara.tv/videos/gprj1toqzt7grj5j?language=en', 'https://ecchi.iwara.tv/videos/j9vq2sz5yte7qq4z?language=en', 'https://ecchi.iwara.tv/videos/k9wkwckgvhqa9zjr?language=en', 'https://ecchi.iwara.tv/videos/kky6qszmbtzevgz6?language=en', 'https://ecchi.iwara.tv/videos/lkkwmhl85hw6vdoy?language=en', 'https://ecchi.iwara.tv/videos/lnllkcl85hw7zaaz?language=en', 'https://ecchi.iwara.tv/videos/lqxazukwlh8rv6md?language=en', 'https://ecchi.iwara.tv/videos/nab1vigyjtp8wmpb?language=en', 'https://ecchi.iwara.tv/videos/o13opi6z0c1wwwjy?language=en', 'https://ecchi.iwara.tv/videos/o6v4jfrj9t6rqwze?language=en', 'https://ecchi.iwara.tv/videos/0npgys9lbizoeeeq?language=en', 'https://ecchi.iwara.tv/videos/57q8yiboghwkevg8?language=en', 'https://ecchi.iwara.tv/videos/5adrycboghwrx8m9?language=en', 'https://ecchi.iwara.tv/videos/86wrru32ytl3vk93?language=en', 'https://ecchi.iwara.tv/videos/87pkbs32ytlv3jrb?language=en', 'https://ecchi.iwara.tv/videos/a7jo6umbvt8ryvj0?language=en', 'https://ecchi.iwara.tv/videos/ag5vjivylt75wzer?language=en', 'https://ecchi.iwara.tv/videos/b7nwjh4byu39aw6g?language=en', 'https://ecchi.iwara.tv/videos/blm0wc4byu3ybwbr?language=en', 'https://ecchi.iwara.tv/videos/blp3eiv5dtlnv1ar?language=en', 'https://ecchi.iwara.tv/videos/delknho2btk362zx?language=en', 'https://ecchi.iwara.tv/videos/delmnco2btk3oq73?language=en', 'https://ecchi.iwara.tv/videos/dje7buo2btkknlow?language=en', 'https://ecchi.iwara.tv/videos/e41yzsjv9umggyxb?language=en', 'https://ecchi.iwara.tv/videos/ejakwivywtk1am3y?language=en', 'https://ecchi.iwara.tv/videos/exdjdijv9umrmbrw?language=en', 'https://ecchi.iwara.tv/videos/gmwgltxovhoblogy?language=en', 'https://ecchi.iwara.tv/videos/gwewqfxovhogl7bd?language=en', 'https://ecchi.iwara.tv/videos/jlymasdeycwq5p4v?language=en', 'https://ecchi.iwara.tv/videos/jlzyasdeycw7ygqy?language=en', 'https://ecchi.iwara.tv/videos/k40znuzmbtzbon0b?language=en', 'https://ecchi.iwara.tv/videos/kdkgeikgvhqlbjgj?language=en', 'https://ecchi.iwara.tv/videos/kg76kfkgvhqzpkro?language=en', 'https://ecchi.iwara.tv/videos/komebuzmbtzmxlaq?language=en', 'https://ecchi.iwara.tv/videos/odedzt6z0c1j89gm?language=en', 'https://ecchi.iwara.tv/videos/pg5eosd6vcow4j8z?language=en', 'https://ecchi.iwara.tv/videos/q9jlrcy2xtl6llve?language=en', 'https://ecchi.iwara.tv/videos/qjbq7cgzasrjagll?language=en', 'https://ecchi.iwara.tv/videos/qnqm2cgzasr3njlr?language=en', 'https://ecchi.iwara.tv/videos/qnyj1igzasrbbojy?language=en', 'https://ecchi.iwara.tv/videos/r524liklrso8lm7z?language=en', 'https://ecchi.iwara.tv/videos/rga4ltyr9uzgezkr?language=en', 'https://ecchi.iwara.tv/videos/rrx5zcyr9uz4bdzo?language=en', 'https://ecchi.iwara.tv/videos/vb0ems2vkuegaqgz?language=en', 'https://ecchi.iwara.tv/videos/vpzozcrdgue2oorg?language=en', 'https://ecchi.iwara.tv/videos/wbd0bugnlsy0p6ow?language=en', 'https://ecchi.iwara.tv/videos/wglxvfgnlsynkr1v?language=en', 'https://ecchi.iwara.tv/videos/xob2xfyd5uwqwlvn?language=en', 'https://ecchi.iwara.tv/videos/z9xqkfa4aigwjvpe?language=en', 'https://ecchi.iwara.tv/videos/zanowta4aig2r4p3?language=en', 'https://ecchi.iwara.tv/videos/oa39vcrj9t6bjqwa?language=en', 'https://ecchi.iwara.tv/videos/ozdkwt6z0c1kqnov?language=en', 'https://ecchi.iwara.tv/videos/pwqy5hd6vcowg6q8?language=en', 'https://ecchi.iwara.tv/videos/q4z24sgzasr5bobm?language=en', 'https://ecchi.iwara.tv/videos/q6b4yhgzasrmro00?language=en', 'https://ecchi.iwara.tv/videos/qd3zmiy2xtl3mv8y?language=en', 'https://ecchi.iwara.tv/videos/qvmq1hy2xtllezjw?language=en', 'https://ecchi.iwara.tv/videos/rbagwuklrsokopwj?language=en', 'https://ecchi.iwara.tv/videos/rkm4nuyr9uzeevr9?language=en', 'https://ecchi.iwara.tv/videos/rmbqviklrso6dy1p?language=en', 'https://ecchi.iwara.tv/videos/v7yaltrdguev6l3z?language=en', 'https://ecchi.iwara.tv/videos/valw3i2vkuejmmj1?language=en', 'https://ecchi.iwara.tv/videos/vazzpf2vkuejylan?language=en', 'https://ecchi.iwara.tv/videos/vkxazs2vkuer5da1?language=en', 'https://ecchi.iwara.tv/videos/wnbwyi1xquqxym32?language=en', 'https://ecchi.iwara.tv/videos/wx5eatgnlsybdlkl?language=en', 'https://ecchi.iwara.tv/videos/wxoqdignlsyel6v4?language=en', 'https://ecchi.iwara.tv/videos/wxrelignlsya8omd?language=en', 'https://ecchi.iwara.tv/videos/ydrmmh9yjio8qaer?language=en', 'https://ecchi.iwara.tv/videos/z5njbf4anukwdkla?language=en', 'https://ecchi.iwara.tv/videos/zj9mvca4aigk2ekq?language=en', 'https://ecchi.iwara.tv/videos/0e4qzh9lbizye9q9?language=en', 'https://ecchi.iwara.tv/videos/0wlxrf9lbizd5kb2?language=en', 'https://ecchi.iwara.tv/videos/0z0eyu9lbizob4gl?language=en', 'https://ecchi.iwara.tv/videos/2z5pys92aiq43b7x?language=en', 'https://ecchi.iwara.tv/videos/5qg88hboghw0krwe?language=en', 'https://ecchi.iwara.tv/videos/84ygqs32ytloraqo?language=en', 'https://ecchi.iwara.tv/videos/8evjgf32ytlyazyo?language=en', 'https://ecchi.iwara.tv/videos/9e2kpikyxhzqorzy?language=en', 'https://ecchi.iwara.tv/videos/b5jjosv5dtlyjgwk?language=en', 'https://ecchi.iwara.tv/videos/dawbvfo2btkgxyqm?language=en', 'https://ecchi.iwara.tv/videos/djj8wuo2btk9oln9?language=en', 'https://ecchi.iwara.tv/videos/erzbwsvywtk9gqa3?language=en', 'https://ecchi.iwara.tv/videos/ex3rmhvywtkw88p9?language=en', 'https://ecchi.iwara.tv/videos/glkevioqzt7rx2yv?language=en', 'https://ecchi.iwara.tv/videos/j8exesdeycweay1y?language=en', 'https://ecchi.iwara.tv/videos/jjaaytz5yte4gwgk?language=en', 'https://ecchi.iwara.tv/videos/jjr3xuz5yte47m9z?language=en', 'https://ecchi.iwara.tv/videos/l8xvvtl85hwv82ve?language=en', 'https://ecchi.iwara.tv/videos/mbj9zcrjmu8gjwkr?language=en', 'https://ecchi.iwara.tv/videos/mervefrjmu84d0lk?language=en', 'https://ecchi.iwara.tv/videos/nmmxnsgyjtp7yql7?language=en', 'https://ecchi.iwara.tv/videos/ogywlc6z0c19aa7v?language=en', 'https://ecchi.iwara.tv/videos/orzwat6z0c1xv8jz?language=en', 'https://ecchi.iwara.tv/videos/q9lywsgzasreaqbv?language=en', 'https://ecchi.iwara.tv/videos/qemwvfy2xtl8z6lo?language=en', 'https://ecchi.iwara.tv/videos/v4rr6i2vkuewo44n?language=en', 'https://ecchi.iwara.tv/videos/vgmbwt2vkueoyrpo?language=en', 'https://ecchi.iwara.tv/videos/vloybfrdgueedelb?language=en', 'https://ecchi.iwara.tv/videos/wbgbgfgnlsy6epyl?language=en', 'https://ecchi.iwara.tv/videos/wn92jf1xquq132ge?language=en', 'https://ecchi.iwara.tv/videos/zn7dxu4anukygxrv?language=en']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] ytdl-patched version 2022.04.08
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "D:\Program Files\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-28-git-5ee198f9aa-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'downloaded.txt'
[debug] [iwara] Extracting URL: https://ecchi.iwara.tv/videos/03yedh9lbizq1kq8?language=en
[iwara] 03yedh9lbizq1kq8: Downloading webpage
[iwara] [debug] Fetching webpage from https://ecchi.iwara.tv/videos/03yedh9lbizq1kq8?language=en
[iwara] 03yedh9lbizq1kq8: Downloading JSON metadata
[iwara] [debug] Fetching webpage from http://www.iwara.tv/api/video/03yedh9lbizq1kq8
WARNING: [iwara] unable to extract upload_date; please report this issue on  https://github.com/ytdl-patched/ytdl-patched/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Sort order given by user: vbr, abr
[debug] Formats sorted by: hasvid, ie_pref, vbr, abr, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, asr, proto, vext, aext, hasaud, source, id
[debug] Searching for '(?P<extractor>.+)' in '%(uploader)s'
ERROR: type object 'MetadataParserPP' has no attribute 'BACKLOG_UNSET'
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1437, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1531, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1587, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2652, in process_video_result
    info_dict, _ = self.pre_process(info_dict)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3495, in pre_process
    info = self.run_all_pps(key, info)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3489, in run_all_pps
    info = self.run_pp(pp, info)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\postprocessor\common.py", line 29, in run
    ret = func(self, info, *args, **kwargs)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\postprocessor\metadataparser.py", line 68, in run
    next(filter(lambda x: 0, f(info)), None)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\postprocessor\metadataparser.py", line 80, in f
    yield (attribute, info.get(attribute, MetadataParserPP.BACKLOG_UNSET))
AttributeError: type object 'MetadataParserPP' has no attribute 'BACKLOG_UNSET'
```

**Comment by Lesmiscore** [comment]
Cannot reproduce. You did something wrong since it has unknown version to ytdl-patched.

```
$ ./b --parse-metadata "%(uploader)s:%(extractor)s" test:Youtube_2
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&v=yZIXLfi8CZQ
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[youtube] BaW_jenozKc: Requesting localized title
[MetadataParser] Parsed extractor from '%(uploader)s': 'Philipp Hagemeister'
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[download] Destination: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f248.webm
[download] 100% of 965.31KiB in 00:00
[download] Destination: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f251.webm
[download] 100% of 138.96KiB in 00:00
[Merger] Merging formats into "youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].mkv"
^C
ERROR: Interrupted by user
```

**Comment by afterdelight** [comment]
hmm, it fixed itself after i updated to latest version. 

I got other question,
i want to replace archive template with --parse-metadata "uploader:%%(extractor)s" 
 iwara 03yedh9lbizq1kq8 --> uploader_name 03yedh9lbizq1kq8

but i still got  iwara 03yedh9lbizq1kq8  in my download archive. 
how do i fix that?

**Comment by Lesmiscore** [comment]
`--download-archive` isn't for that!
