### ISSUE TITLE
[ABEMA] SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Nosoba** [ytdl-patched/ytdl-patched#75]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

It's been a long time for me to download from abema, but when i'm trying it won't downloading.

But streamlink is work fine, just reporting it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://abema.tv/video/episode/50-20_s1_p1', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched version 2022.12.30.1672360704 [e783a33] (exe_red)
[debug]      from commit e783a338b
[debug]      based on e107c2b8c
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python 3.7.9 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev (setts), ffprobe 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, WebSocketsWrapper-None, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1785 extractors
[AbemaTV] Extracting URL: https://abema.tv/video/episode/50-20_s1_p1
[AbemaTV] Authorizing
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/users
ERROR: [AbemaTV] 50-20_s1_p1: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\abematv.py", line 378, in _real_extract
  File "yt_dlp\extractor\abematv.py", line 250, in _get_device_token
  File "yt_dlp\extractor\common.py", line 1089, in download_content
  File "yt_dlp\extractor\common.py", line 1051, in download_handle
  File "yt_dlp\extractor\common.py", line 914, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 859, in _request_webpage

  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1277, in request
  File "http\client.py", line 1323, in _send_request
  File "http\client.py", line 1272, in endheaders
  File "http\client.py", line 1032, in _send_output
  File "http\client.py", line 972, in send
  File "http\client.py", line 1447, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 841, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3116, in wrapper
  File "yt_dlp\YoutubeDL.py", line 4021, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "yt_dlp\utils.py", line 1547, in https_open
  File "urllib\request.py", line 1352, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

**Comment by october262** [comment]
try adding --no-check-certificate to your command and see if that works.

**Comment by Nosoba** [comment]
> try adding --no-check-certificate to your command and see if that works.

Thanks! It worked!
