### ISSUE TITLE
-U app update not working

### ISSUE THREAD

**Issue by bachig26** [ytdl-patched/ytdl-patched#78]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [ ] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```
ytdl-pat -U
Available version: stable@2023.03.24.1679618280, Current version: stable@2023.03.03.1
Current Build Hash: 2a5c450e35f2f5bc67bc6f2fbaa78288d4b5c3607e89cddb37bfd6180eb70da9
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 22, in <module>
  File "yt_dlp\__init__.py", line 999, in main
  File "yt_dlp\__init__.py", line 967, in _real_main
  File "yt_dlp\update.py", line 284, in update
  File "yt_dlp\update.py", line 273, in check_update
  File "yt_dlp\update.py", line 223, in has_update
  File "yt_dlp\update.py", line 213, in new_version
  File "yt_dlp\compat\functools.py", line 25, in __get__
  File "yt_dlp\update.py", line 171, in _tag
  File "yt_dlp\update.py", line 234, in _download
  File "yt_dlp\YoutubeDL.py", line 3133, in wrapper
  File "yt_dlp\YoutubeDL.py", line 4044, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
[5588] Failed to execute script '__main__' due to unhandled exception!
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ytdl-pat -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched version 2023.03.03.1 [270703da4] (exe_red)
[debug]      from commit 270703da4
[debug]      based on 9acf1ee25
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python 3.7.9 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg n5.1.2-12-g7268323193-20230218 (setts), ffprobe n5.1.2-12-g7268323193-20230218, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, WebSocketsWrapper-None, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1817 extractors
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/ytdl-patched/releases/latest
Available version: stable@2023.03.24.1679618280, Current version: stable@2023.03.03.1
Current Build Hash: 2a5c450e35f2f5bc67bc6f2fbaa78288d4b5c3607e89cddb37bfd6180eb70da9
[debug] Downloading _update_spec from https://github.com/ytdl-patched/ytdl-patched/releases/latest/download/_update_spec
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 22, in <module>
  File "yt_dlp\__init__.py", line 999, in main
  File "yt_dlp\__init__.py", line 967, in _real_main
  File "yt_dlp\update.py", line 284, in update
  File "yt_dlp\update.py", line 273, in check_update
  File "yt_dlp\update.py", line 223, in has_update
  File "yt_dlp\update.py", line 213, in new_version
  File "yt_dlp\compat\functools.py", line 25, in __get__
  File "yt_dlp\update.py", line 171, in _tag
  File "yt_dlp\update.py", line 234, in _download
  File "yt_dlp\YoutubeDL.py", line 3133, in wrapper
  File "yt_dlp\YoutubeDL.py", line 4044, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
[516] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by Lesmiscore** [comment]
The error should be fixed in the next version; update manually once it become available
